// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANIdPtOifeX21qpt9uE6IzPLZUCjB_QiQ',
    appId: '1:458427266602:web:69036a06d8b4b370f6b553',
    messagingSenderId: '458427266602',
    projectId: 'app-notasorg',
    authDomain: 'app-notasorg.firebaseapp.com',
    storageBucket: 'app-notasorg.firebasestorage.app',
    measurementId: 'G-2PMDT2FJ1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU7QRYnl75NALbolcMyhz0Q_KXtF3aj4Q',
    appId: '1:458427266602:android:10345d56886e8a64f6b553',
    messagingSenderId: '458427266602',
    projectId: 'app-notasorg',
    storageBucket: 'app-notasorg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfG3ObxrwdJks6nC6AZSBo6OEolA0hCyM',
    appId: '1:458427266602:ios:69a9cf7d811ec048f6b553',
    messagingSenderId: '458427266602',
    projectId: 'app-notasorg',
    storageBucket: 'app-notasorg.firebasestorage.app',
    iosBundleId: 'com.example.appNotasorg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfG3ObxrwdJks6nC6AZSBo6OEolA0hCyM',
    appId: '1:458427266602:ios:69a9cf7d811ec048f6b553',
    messagingSenderId: '458427266602',
    projectId: 'app-notasorg',
    storageBucket: 'app-notasorg.firebasestorage.app',
    iosBundleId: 'com.example.appNotasorg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANIdPtOifeX21qpt9uE6IzPLZUCjB_QiQ',
    appId: '1:458427266602:web:19ceab6c8a62e7b9f6b553',
    messagingSenderId: '458427266602',
    projectId: 'app-notasorg',
    authDomain: 'app-notasorg.firebaseapp.com',
    storageBucket: 'app-notasorg.firebasestorage.app',
    measurementId: 'G-1BSP886088',
  );
}
